version: '3'

services:
  backend:
    build:
      context: ./backend # Indica la ubicación de tu backend
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/myapp # Refleja la nueva ubicación
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: marketpeople
      POSTGRES_PASSWORD: marketpeople
      POSTGRES_DB: postgres_MP
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:


